export const user_permissions_updated = "USER_UPDATED"
export const user_added = "USER_ADDED"
export const user_deleted = "USER_DELETED"
export const superuser_added = "SUPERUSER_ADDED"
export const superuser_deleted = "SUPERUSER_DELETED"
export const adminState_changed = "ADMINSTATE_CHANGED"