export const element_selected = "ELEMENT_SELECTED"
export const element_edited = "ELEMENT_EDITED"
export const element_updated = "ELEMENT_UPDATED"
export const element_added = "ELEMENT_ADDED"
export const element_deleted = "ELEMENT_DELETED"
export const section_added = "SECTION_ADDED"
export const section_deleted = "SECTION_DELETED"