export const element_selected = "ELEMENT_SELECTED"
export const element_edited = "ELEMENT_EDITED"
export const element_updated = "ELEMENT_UPDATED"
export const element_added = "ELEMENT_ADDED"
export const element_deleted = "ELEMENT_DELETED"
export const search_element_added = "SEARHC_ELEMENT_ADDED"
export const search_setted_to_null = "SEARCH_SETTED_TO_NULL"