export const GET_GENRE_WITH_MORE_SONGS= "GET_GENRE_WITH_MORE_SONGS ";
export const GET_ARTIST_WITH_MORE_ALBUMS = "GET_ARTIST_WITH_MORE_ALBUMS";
export const GET_LONGEST_SONG = 'GET_LONGEST_SONG';
export const GET_GENRE_BY_DURATION = 'GET_GENRE_BY_DURATION';
export const GET_MORE_COLABORATIVE_ARTIST = 'GET_MORE_COLABORATIVE_ARTIST';
export const GET_MORE_RECENT_ABLUMS = 'GET_MORE_RECENT_ABLUMS';
export const GET_USERS_WITH_MORE_ALBUMS_ADDED = 'GET_USERS_WITH_MORE_ALBUMS_ADDED;'