export const verified_user_added = "VERIFIED_USER_ADDED"
export const user_added = "USER_ADDED"
export const set_empty = "SET_EMPTY"
export const added_to_order = "ADDED_TO_ORDER"
export const addBoughtTrack = "ADD_BOUGH_TRACK"